version: "3.7"
services:
  duckdns:
    image: linuxserver/duckdns:latest
    container_name: duckdns
    networks:
     - outside
    environment:
#      - PUID=1000 #optional
#      - PGID=1000 #optional
      - TZ=America/Sao_Paulo
      - SUBDOMAINS=<subdominio>
      - TOKEN=<seutoken>
      - LOG_FILE=true #optional
    volumes:
      - duckdns_config:/config #optional
    restart: unless-stopped

volumes:
  duckdns_config:

networks:
  outside:
    external: true
    name: outside
